stages:
  - test
  - build

backend_unit_test:
  image: openjdk:11-jre-slim
  stage: test
  script:
    - ./mvnw test

backend_build:
  image: openjdk:11-jre-slim
  stage: build
  script:
    - ./mvnw package -DskipTests=true
