pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                ./mvnw test
            }
        }
        stage('Build') {
            steps {
                ./mvnw package -DskipTests=true
            }
        }
    }
}