spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test?serverTimezone=UTC"
    username: "cyril"
    password: "azerty"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: cyril
    password: azerty
